### ISSUE TITLE
Error on execution

### ISSUE THREAD

**Issue by pollywannacracka** [gnebbia/pdlist#1]
Installed as written and get the following error. Any ideas? Thanks!:

Traceback (most recent call last):
  File "/usr/local/bin/pdlist", line 11, in <module>
    load_entry_point('pdlist==0.1.0', 'console_scripts', 'pdlist')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/pdlist-0.1.0-py2.7.egg/pdlist/main.py", line 17, in <module>
    import pdlist.source.dnsdumpster as dd
  File "/usr/local/lib/python2.7/dist-packages/pdlist-0.1.0-py2.7.egg/pdlist/source/dnsdumpster.py", line 15, in <module>
    from dnsdumpster.DNSDumpsterAPI import DNSDumpsterAPI
ImportError: No module named DNSDumpsterAPI

-------------------
$sudo pip install -r requirements.txt
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (2.20.0)
Requirement already satisfied: dnsdumpster in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (0.5)
Requirement already satisfied: bs4 in /usr/local/lib/python2.7/dist-packages (from dnsdumpster->-r requirements.txt (line 2)) (0.0.1)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python2.7/dist-packages (from bs4->dnsdumpster->-r requirements.txt (line 2)) (4.6.3)

**Comment by cirillo** [comment]
I believe this is a python version issue. While its not stated in the readme, try using python3 instead of python2.

**Comment by pollywannacracka** [comment]
Interesting, here is the output when I use Python3. What am I missing:

python3 pdlist example.com -o example.txt
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "pdlist/__main__.py", line 13, in <module>
    from pdlist.main import main
ModuleNotFoundError: No module named 'pdlist

**Comment by cirillo** [comment]
You would also have to install the requirements with pip3 and the package as python3.

**Comment by gnebbia** [comment]
Exactly, as cirillo said, the software is only compatible with python3.
I modified the README to reflect this. As a suggestion, if you want an easy switch between python versions, I suggest pyenv.
